# Generated by Django 6.0.3 on 2026-04-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-id'], 'verbose_name': 'Локация пользователя', 'verbose_name_plural': 'Локации пользователей'},
        ),
        migrations.AddField(
            model_name='location',
            name='weather_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='weather_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
